-- 1. Profiles (Extends Supabase Auth)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT NOT NULL,
  full_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1b. User Credentials (For custom email/password auth)
CREATE TABLE user_credentials (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Trips (The Core Object)
CREATE TABLE trips (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  created_by UUID REFERENCES profiles(id),
  name TEXT NOT NULL, -- e.g. "Goa 2024"
  destination TEXT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  budget_tier TEXT, -- 'Low', 'Medium', 'High'
  categories TEXT[], -- ['Adventure', 'Food', 'Off-Roading']
  settings JSONB DEFAULT '{"return_to_start": false}',
  status TEXT DEFAULT 'DRAFT', -- 'DRAFT', 'ACTIVE', 'COMPLETED'
  invite_code UUID DEFAULT uuid_generate_v4(), -- For sharing links
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Trip Participants (Many-to-Many Link)
CREATE TABLE trip_participants (
  trip_id UUID REFERENCES trips(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  role TEXT DEFAULT 'MEMBER', -- 'ADMIN', 'MEMBER'
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (trip_id, user_id)
);

-- 4. Trip Days (The State Machine)
CREATE TABLE trip_days (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  trip_id UUID REFERENCES trips(id) ON DELETE CASCADE,
  day_date DATE NOT NULL,
  day_index INT NOT NULL, -- Day 1, Day 2...
  status TEXT DEFAULT 'PENDING', -- 'PENDING', 'VOTING', 'LOCKED'
  start_location JSONB, -- The starting point for this specific day
  UNIQUE(trip_id, day_index)
);

-- 5. Place Candidates (The Options generated by AI)
CREATE TABLE place_candidates (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  day_id UUID REFERENCES trip_days(id) ON DELETE CASCADE,
  time_slot TEXT NOT NULL, -- 'morning', 'afternoon', 'evening'
  google_place_id TEXT NOT NULL,
  name TEXT NOT NULL,
  location JSONB NOT NULL, -- { lat: ..., lng: ... }
  rating NUMERIC,
  photo_ref TEXT,
  gemini_vibe_check TEXT, -- "Great sunset spot, crowded."
  is_jain_friendly BOOLEAN DEFAULT FALSE,
  is_offroad_suitable BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Votes (User Feedback)
CREATE TABLE votes (
  candidate_id UUID REFERENCES place_candidates(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  vote_value INT DEFAULT 1, -- 1 (Upvote), -1 (Downvote)
  PRIMARY KEY (candidate_id, user_id)
);

-- 7. Chat Messages
CREATE TABLE chat_messages (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  trip_id UUID REFERENCES trips(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id),
  content TEXT NOT NULL,
  is_system_message BOOLEAN DEFAULT FALSE, -- "User X joined the trip"
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Expenses (Bill Splitter)
CREATE TABLE expenses (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  trip_id UUID REFERENCES trips(id) ON DELETE CASCADE,
  payer_id UUID REFERENCES profiles(id),
  amount NUMERIC NOT NULL,
  description TEXT,
  split_details JSONB, -- { "user_a": 50, "user_b": 50 }
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on all tables
ALTER TABLE trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE trip_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE place_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

-- Policy: "Users can view trips they are participating in"
CREATE POLICY "View own trips" ON trips
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM trip_participants
    WHERE trip_participants.trip_id = trips.id
    AND trip_participants.user_id = auth.uid()
  )
);

-- Policy: "Users can insert into trips if they are participants"
CREATE POLICY "Edit own trips" ON trips
FOR UPDATE USING (
  EXISTS (
    SELECT 1 FROM trip_participants
    WHERE trip_participants.trip_id = trips.id
    AND trip_participants.user_id = auth.uid()
  )
);
